from footings.data_dictionary import data_dictionary, def_column


@data_dictionary
class SharedOutputTerms:
    """Shared columns for projection and valuation models as well as active and disabled models."""

    MODEL_VERSION = def_column(
        dtype="string", description="The model version generated by versioneer."
    )
    LAST_COMMIT = def_column(dtype="string", description="The last git commit.")
    RUN_DATE_TIME = def_column(
        dtype="datetime64[ns]", description="The run date and time."
    )
    SOURCE = def_column(dtype="string", description="The underlying policy model used.")
