import pandas as pd
from footings import define_parameter, define_meta

from .__init__ import __version__ as MOD_VERSION
from .__init__ import __git_revision__ as GIT_REVISION

param_n_simulations = define_parameter(
    description="The number of simulations to run.", default=1000, dtype=int,
)

param_seed = define_parameter(
    description="The seed passed to numpy.random.seed.", default=42, dtype=int,
)

param_valuation_dt = define_parameter(
    description="The valuation date which reserves are based.", dtype=pd.Timestamp,
)

param_assumption_set = define_parameter(
    description="""The assumption set to use for running the model. Options are :
    
        * `stat`
        * `gaap`
        * `best-estimate`
    """,
    dtype=str,
    allowed=["stat", "gaap", "best-estimate"],
)

param_disabled_extract = define_parameter(
    description="The disabled life extract to use. See idi_model/schema/disabled_life_schema.yaml for specification.",
    dtype=pd.DataFrame,
)

param_active_base_extract = define_parameter(
    description="""The active life base extract to use. See idi_model/schema/extract-active-lives-base.yaml for specification.""",
    dtype=pd.DataFrame,
)

param_active_rider_extract = define_parameter(
    description="""The active life rider extract to use. See idi_model/schema/extract-active-lives-riders.yaml for specification.""",
    dtype=pd.DataFrame,
)

param_model_type = define_parameter(
    description="""The policy model to deploy. Options are :

        * `determinstic`
        * `stochastic`
    """,
    dtype=str,
    allowed=["deterministic", "stochastic"],
)

param_net_benefit_method = define_parameter(
    description="""The net benefit method. Options are :

        * `NLP` = Net level premium
        * `PT1` = 1 year preliminary term
        * `PT2` = 2 year preliminary term
    """,
    dtype=str,
    allowed=["NLP", "PT1", "PT2"],
)

meta_model_version = define_meta(meta=MOD_VERSION, dtype=str, description="The model version generated by versioneer.")
meta_last_commit = define_meta(meta=GIT_REVISION, dtype=str, description="The last git commmit.")
meta_run_date_time = define_meta(meta=pd.to_datetime("now"), dtype=pd.Timestamp, description="The run date and time.")