from footings.data_dictionary import data_dictionary, def_column

from .extracts import ActiveLivesBaseExtract, DisabledLivesBaseExtract

_MODEL_VERSION = def_column(
    dtype="string", description="The model version generated by versioneer."
)
_LAST_COMMIT = def_column(dtype="string", description="The last git commit.")
_RUN_DATE_TIME = def_column(dtype="datetime64[ns]", description="The run date and time.")
_SOURCE = def_column(dtype="string", description="The underlying policy model used.")


#########################################################################################
# Active Lives Valuation Output
#########################################################################################


@data_dictionary
class ActiveLivesValOutput:
    """Active lives valuation output."""

    MODEL_VERSION = _MODEL_VERSION
    LAST_COMMIT = _LAST_COMMIT
    RUN_DATE_TIME = _RUN_DATE_TIME
    SOURCE = _SOURCE
    POLICY_ID = ActiveLivesBaseExtract.def_column("POLICY_ID")
    COVERAGE_ID = ActiveLivesBaseExtract.def_column("COVERAGE_ID")
    DATE_BD = def_column(
        dtype="datetime64[ns]", description="Projected begining policy duration date."
    )
    DATE_ED = def_column(
        dtype="datetime64[ns]", description="Projected ending policy duration date."
    )
    DURATION_YEAR = def_column(dtype="int", description="Projected policy duration year.")
    LIVES_BD = def_column(
        dtype="float16",
        description="Projected average lives inforce begining policy duration.",
    )
    LIVES_MD = def_column(
        dtype="float16",
        description="Projected average lives inforce mid-point of policy duration.",
    )
    LIVES_ED = def_column(
        dtype="float16",
        description="Projected average lives inforce ending policy duration.",
    )
    DISCOUNT_BD = def_column(
        dtype="float16", description="Discount factor used begining policy duration."
    )
    DISCOUNT_MD = def_column(
        dtype="float16", description="Discount factor used mid-point of policy duration."
    )
    DISCOUNT_ED = def_column(
        dtype="float16", description="Discount factor used ending policy duration."
    )
    BENEFIT_AMOUNT = def_column(dtype="float16", description="Projected benefit amount.")
    FINAL_INCIDENCE_RATE = def_column(
        dtype="float16",
        description="Final incidence rate with margin and sensitivites applied.",
    )
    BENEFIT_COST = def_column(
        dtype="float16",
        description="Projected benefit cost (PV future benefits x incidence rate).",
    )
    PVFB = def_column(dtype="float16", description="Present value of future benefits.",)
    PVFNB = def_column(
        dtype="float16", description="Present value of future bet benefits.",
    )
    ALR_BD = def_column(
        dtype="float16", description="Projected ALR amount at begining policy duration.",
    )
    ALR_ED = def_column(
        dtype="float16", description="Projected ALR amount at ending policy duration.",
    )
    ALR_DATE = def_column(
        dtype="datetime64[ns]",
        description="Projected valuation dates using val date as base.",
    )
    ALR = def_column(
        dtype="float16",
        description="Projected ALR amount as of projected valuation date.",
    )


#########################################################################################
# Disabled Lives Valuation Output
#########################################################################################


@data_dictionary
class DisabledLivesValOutput:
    """Disabled lives valuation output."""

    MODEL_VERSION = _MODEL_VERSION
    LAST_COMMIT = _LAST_COMMIT
    RUN_DATE_TIME = _RUN_DATE_TIME
    SOURCE = _SOURCE
    POLICY_ID = DisabledLivesBaseExtract.def_column("POLICY_ID")
    CLAIM_ID = DisabledLivesBaseExtract.def_column("CLAIM_ID")
    COVERAGE_ID = DisabledLivesBaseExtract.def_column("COVERAGE_ID")
    DATE_BD = def_column(
        dtype="datetime64[ns]", description="Projected begining claim duration date."
    )
    DATE_ED = def_column(
        dtype="datetime64[ns]", description="Projected ending claim duration date."
    )
    DURATION_YEAR = def_column(dtype="int", description="Projected claim duration year.")
    DURATION_MONTH = def_column(
        dtype="int", description="Projected claim duration month."
    )
    BENEFIT_AMOUNT = def_column(dtype="float16", description="Projected benefit amount.")
    CTR = def_column(
        dtype="float16",
        description="Final claim termination rate with margin and sensitivites applied.",
    )
    LIVES_BD = def_column(
        dtype="float16",
        description="Projected average lives inforce begining claim duration.",
    )
    LIVES_MD = def_column(
        dtype="float16",
        description="Projected average lives inforce mid-point of claim duration.",
    )
    LIVES_ED = def_column(
        dtype="float16",
        description="Projected average lives inforce ending claim duration.",
    )
    DISCOUNT_BD = def_column(
        dtype="float16", description="Discount factor used begining claim duration."
    )
    DISCOUNT_MD = def_column(
        dtype="float16", description="Discount factor used mid-point of claim duration."
    )
    DISCOUNT_ED = def_column(
        dtype="float16", description="Discount factor used ending claim duration."
    )
    PVFB_BD = def_column(
        dtype="float16",
        description="Present value of future benefits begining claim duration.",
    )
    PVFB_ED = def_column(
        dtype="float16",
        description="Present value of future benefit ending claim duration.",
    )
    DATE_DLR = def_column(
        dtype="datetime64[ns]",
        description="Projected valuation dates using val date as base.",
    )
    DLR = def_column(
        dtype="float16",
        description="Projected DLR amount as of projected valuation date.",
    )
